services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doodleking-server
    ports:
      - "8080:8080"
    depends_on:
      - server_db
      - redis
    networks:
      - backend
    environment:
      DB_TYPE: mysql
      DB_HOST: server_db
      DB_PORT: 3306
      DB_DATABASE: doodleking
      DB_USERNAME: root
      DB_PASSWORD: mdominic0@
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_SECRET: session-secret
      LOGGER_DIR: /logs
    volumes:
      - ./logs:/logs

  server_db:
    image: mysql:8.0
    container_name: server_db
    environment:
      MYSQL_ROOT_PASSWORD: mdominic0@
      MYSQL_DATABASE: doodleking
    ports:
      - "3306:3306"
    volumes:
      - ./db/server:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis:/data
    networks:
      - backend

networks:
  backend: