name: main

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 소스 코드 체크아웃
      - uses: actions/checkout@v3

      # 2. 현재 디렉토리 구조 확인
      - name: Show current directory structure
        run: |
          pwd
          ls -R

      # 3. Java 설정
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 4. resources 디렉토리 생성 및 application.properties 생성
      - name: Ensure resources directory exists
        run: mkdir -p ./src/main/resources

      - name: Make application.properties
        run: echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/application.properties

      - name: Verify application.properties
        run: cat ./src/main/resources/application.properties

      # 5. Gradle 빌드
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test
      
      # 6. 빌드 결과를 원격 서버로 복사
      - name: Copy JAR file to remote
        uses: appleboy/scp-action@master
        with:
          username: seojkim0128
          host: ${{ secrets.GCP_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./build/libs/*.jar"
          target: "/home/seojkim0128/Server/cicd"

      # 7. 배포 스크립트 실행
      - name: Execute deploy script on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: seojkim0128
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/seojkim0128/Server/cicd
            chmod +x deploy.sh
            ./deploy.sh
