name: main

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 소스 코드 체크아웃
      - uses: actions/checkout@v3

      # 2. 현재 디렉토리 구조 확인
      - name: Show current directory structure
        run: |
          pwd
          ls -R

      # 3. Java 설정
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # 4. application.properties 생성
      - name: Ensure resources directory exists
        run: mkdir -p ./src/main/resources

      - name: Make application.properties
        run: echo "${{ secrets.PROPERTIES }}" > ./src/main/resources/application.properties
            
      - name: Verify application.properties
        run: cat ./src/main/resources/application.properties
         
      # 5. Gradle 빌드
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: .

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        working-directory: .
      
      # 6. 빌드 아티팩트 업로드
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./build/libs/*.jar

      # 7. JAR 파일 원격 서버로 복사
      - name: Copy JAR file to remote
        uses: appleboy/scp-action@master
        with:
          username: seojkim0128
          host: ${{ secrets.GCP_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./build/libs/*.jar"
          target: "/home/seojkim0128/Server/cicd"

      # 8. 배포 스크립트 복사
      - name: Copy deploy script file to remote
        uses: appleboy/scp-action@master
        with:
          username: seojkim0128
          host: ${{ secrets.GCP_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./cicd/deploy.sh"
          target: "/home/seojkim0128/Server/cicd"

      # 9. 배포 스크립트 실행
      - name: Execute deploy script
        uses: appleboy/ssh-action@master
        with:
          username: seojkim0128
          host: ${{ secrets.GCP_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            chmod +x /home/seojkim0128/Server/cicd/deploy.sh
            sh /home/seojkim0128/Server/cicd/deploy.sh
